classDiagram 
  UserAccountModel <|-- IUserAccountModel
  UserProfileModel <|-- IUserProfileModel


  

  class UserAccountModel{
    
  }

  class IUserAccountModel{
    <<interface>>
  }
  class UserProfileModel{

  }
  class IUserProfileModel{
    <<interface>>

  }
