sequenceDiagram
participant u as User
participant e as Entry Point
participant usm as UserSecurityManager<br>(Manager Layer)
participant ss as SaltingService<br>(Services Layer)
participant uc as UserService<br>(Services Layer)
participant dg as SQLServerUserTarget<br>(Data Gateway)
participant da as SQLServerDAO
participant ds as Data Store

Note Right of e: Assume something in the entry point<br>called the manager to do create a user
e->>+usm: Entry Point calls upon<br>`Response createValidUser(string userName, dateTime DOB)`<br>to create a new user
    Note over e,usm: Response createValidUser(string userName, dateTime DOB)

usm->>usm: UserSecurityManager verifies that<br>the user is within the age range
usm->>usm: UserSecurityManager verifies that<br>the username is valid

usm->>+ss: UserSecurityManager calls upon<br>`uint saltingService.generateRandomSalt()`<br>to get a salt for the user
    Note over ss,usm: uint saltingService.generateRandomSalt()
ss->>-usm: SaltingService returns a randomly generated salt\

usm->>+uc: UserSecurityManager calls upon<br>`Response createUser(string username, int salt)`<br>to create the user with the salt
    Note over usm,uc: Response createUser(string username, int salt)

uc->>+dg: UserService calls upon<br>`Response writeUser(string userName, int salt, dateTime dateOfCreation)`<br>to pass data to be written to the database
    Note over uc,dg: Response writeUser(string userName, int salt, dateTime dateOfCreation)

dg->>+da: SqlServerUserTarget calls upon<br>`Response executeWriteSQL(sqlcommand sql)`<br>to write the sql
    Note over dg,da: Response executeWriteSQL(string sql)

da->>+ds: SqlServerDAO calls upon<br>`cmd.ExecuteNonQuery()`<br>to execute the sql command
    Note over da,ds: cmd.ExecuteNonQuery()

ds->>ds: User account is successfull<br>written to the Data Store

ds-->>-da: Database returns the number of rows affected

da-->>-dg: Response object returned with<br>`Response.ReturnValue` equal to the retrieved value

dg-->>-uc: Response object returned with<br>`Response.SafeToRetry` equal to false

uc-->>-usm: Response object returned

usm-->>e: Response object returned
deactivate usm
