sequenceDiagram

%% See BRD UA-2 for additional context

participant ml as Manager Layer
participant as as AuthService<br>(Services Layer)
participant uc as UserService<br>(Services Layer)
participant dg as SqlDbUserTarget<br>(Data Gateway)
participant da as SQLServerDAO
participant ds as Data Store

ml->>+uc: RecoverUser( userName: String): IResponse
    Note over ml,uc: Manager Layer calls upon<br>` RecoverUser( userName: String): IResponse`<br>to recover the user

%% UserService should check/ validate data passed through
%% uc->>+uc: UserService checks to see if the `IResponse` object has errors or not

    %% Modify the user
    uc->>+dg: RecoverUserAccountSql(userName: String):  IResponse 
    Note over uc,dg: UserService calls upon<br>`RecoverUserAccountSql(userName: String): IResponse `<br>to pass user data to be written to a parameterized SqlCommand

    dg->>dg: SqlDbUserTarget creates Parameterized SqlCommand

    dg->>+da: executeWriteSQL(sql: SqlCommand): IResponse
    Note over dg,da: SqlServerUserTarget calls upon<br>`executeWriteSQL(sql: SqlCommand): IResponse`<br>to write the sql

    da->>+ds: SqlCommand.ExecuteNonQuery()
    Note over da,ds: SqlServerDAO calls upon<br>`SqlCommand.ExecuteNonQuery()`<br>to execute the sql command

    ds->>ds: User account data is successfully<br>modified in the Data Store

    ds-->>-da: Database returns the number of rows affected

    da-->>-dg: IResponse object returned with<br>`Response.ReturnValue` equal to the retrieved value

    dg-->>-uc: IAccountResponse object returned with<br>`IAccountResponse.HasError` equal to false

    uc-->>-ml: IAccountResponse object returned
