sequenceDiagram
participant u as Browser
participant e as DonateYourCarPoint<br>(Entry Point)
participant m as DonateYourCarManager<br>(Manager Layer)
participant s as CharityRetrievalService<br>(Service Layer)
participant ll as LogService<br>(Services Layer)
participant dt as SqlDbCharityTarget<br>(Data Gateway)
participant da as SqlServerDAO<br>(Data Access Object)
participant ds as Data Store<br>(Sql Server)

