sequenceDiagram
participant U as User
participant V as View
participant M as Manager
participant S as LogService (Service)
participant DG as SqlDbLogTarget (Data Gateway)
participant DA as SqlServerDAO
participant DS as Data Store

U->>V: The user interacts with the view
V->>M: The view calls on the manager<br>to save a log to the Data Store
M->>+S: The manager calls upon `LogService.Log()`<br>and passes in `logLevel`, `logCategory`,<br>and `logMessage` to information it needs<br>to log to the Data Store
S->>+DG: The `LogService` calls upon<br>`SqlDbLogTarget.Write()` to create <br> a parameterized SQL command with<br>the log information
DG->>+DA: The `SqlDbLogTarget` calls upon <br> `SqlServerDAO.executeWriteOnly()`<br>to connect to the database and<br>execute the SQL command
DA->>+DS: The `SqlServerDAO` calls upon<br>`SqlCommand.ExecuteNonQuery()`<br>to write the data to the data store
DS->>+DS: The Data Store processes<br> the SQL Code

rect rgba(127,127,127,.1)
alt Data Store fails to write the Log information
    DS->>DA: The Data Store fails to write the<br>Log information to the data store
    rect rgba(127,127,127,.2)
    alt The error is recoverable
        DA->>DG: The `SqlServerDAO`<br>returns a `Response` object with<br>`Response.HasError` set to `true` and<br>`Response.IsSafeToRetry` set to `true`
        rect rgba(127, 127, 127, 0.2)
        loop Until `Response.RetryAttempts` is equal to 3
            par
                DG->>DA: The `SqlDbLogTarget` calls upon <br> `SqlServerDAO.executeWriteOnly()`<br>to connect to the database and<br>execute the SQL command
                DG->>DG: The `SqlDbLogTarget` will increment the `Response.RetryAttempts` by 1
            end
            DA->>DS: The `SqlServerDAO` calls upon<br>`SqlCommand.ExecuteNonQuery()`<br>to write the data to the data store
        end
        end
    else The error is unrecoverable
        DA->>DG: The `SqlServerDAO`<br>returns a `Response` object with<br>`Response.HasError` set to `true` and<br>`Response.IsSafeToRetry` set to `false`
        DG->>S: Response Object is found to have error<br> Error handling is applied appropriately
    end
    end
else Data Store succeeds to write the Log information
    DS-->>-DA: SQL Written Successfully
    DA->>-DG: Returns `Response` object with outcome
    DG->>-S: Response Object is confirmed to be successful<br>Logging is finalized
    deactivate S
end
end