sequenceDiagram
participant V as View Layer
participant M as Manager Layer
participant S as LogService (Service Layer)
participant DG as SqlDbLogTarget (Data Access Layer)
participant DA as SqlServerDAO (Data Access Layer)
participant DS as SqlServer (Data Store Layer)

V->>M: The view calls on the manager<br>to save a log to the Data Store

M->>+S: The manager calls upon<br>`CreateLog(string logLevel, string logCategory, string logContext, string? createdBy = null)`<br>and passes in logLevel, logCategory,<br>logMessage, and optionally logCreatedBy to create<br>a Log object
    Note over M,S: IResponse CreateLog(string logLevel, string logCategory, string logContext, string? createdBy = null)
S->>S: LogService creates Log object

S->>+DG: The LogService calls upon<br>`SqlDbLogTarget.Write(ILog log)` to create <br> a parameterized SqlCommand with<br>the created Log object
    Note over S,DG: IResponse SqlDbLogTarget.Write(ILog log)

DG->>DG: SqlDbLogTarget creates Parameterized SqlCommand

rect rgba(127, 127, 127, .2)
loop Until `Response.IsSafeToRetry` = false or `Response.RetryAttempts` = 3

    DG->>+DA: The SqlDbLogTarget calls upon <br> `SqlServerDAO.ExecuteWriteOnly(SqlCommand sql)`<br>to connect to SqlServer and<br>execute the generated SqlCommand
        Note over DG,DA: IResponse SqlServerDAO.ExecuteWriteOnly(SqlCommand sql)

    DA->>+DS: The SqlServerDAO calls upon<br>`SqlCommand.ExecuteNonQuery()`<br>to exectue query on the SqlServer
        Note over DA,DS: int SqlCommand.ExecuteNonQuery()

    DS->>DS: The SqlServer processes<br> the SQL Code

    #Returning
    DS-->>-DA: The SqlServer was unable to write the log <br>and returns an error

    DA-->>DA: The SQLServerDAO checks the returned<br>value from the SqlServer for errors
    DA-->>DA: The SQLServerDAO creates a new `Response`<br>object with `Response.HasError` = true,<br> `Response.IsSafeToRetry` = true
    DA-->>-DG: The SQLServerDAO returns the `Response` object

    DG-->>DG: The `SqlDbLogTarget` checks<br>`Response.HasError` is equal to true,<br>`Response.IsSafeToRetry` is equal to true, and<br>`Response.RetryAttempts` is less than 3
    
    rect rgba(127, 127, 127, .1)
    alt If `Response.RetryAttempts` is less than 3
        DG-->>DG: The `SqlDbLogTarget` increments<br>`Response.RetryAttempts` by 1
    else
        DG-->>DG: The `SqlDbLogTarget` sets<br>`Response.IsSafeToRetry` equal to false
    end
    end
end
end
DG-->>-S: The `SqlDbLogTarget` returns the `Response` object

S-->>-M: The `LogService` returns the `Response` object