sequenceDiagram
participant u as Browser
participant az as AuthN/AuthZ<br>(Entry Point)
participant e as CarNewsCenterEntryPoint<br>(Entry Point)
participant vpm as CarNewsCenterManager<br>(Manager Layer)
participant vps as NotificationService<br>(Services Layer)
participant ll as LogService<br>(Services Layer)
participant dg as SqlDCarNewsCenterTarget<br>(Data Gateway)
participant da as SqlServerDAO<br>(Data Access Object)
participant ds as Data Store<br>(Sql Server)

Note Left of u: User attempts to to create new vehicle profile
u->>+az: CheckToken() 
    Note over u,az: *Temporary method signature*<br>Browser checks for<br>authorized access to the page.<br>See authorization success case
az-->>-u: Return valid check

u->>+e: ViewAlert() : IActionResult
    Note over u,e: Invoked when user ask for recall status and ViewVehicleSafetyRecall will call this <br>if there is a recall after it updates the db

    e->>+vpm:  ViewAlert(vin: string) : IResponse
        Note over e,vpm: Entry point calls upon manager<br>to create vehicle profiles
        
        vpm->>vpm: Validate Parameters

        vpm->>+vps:   ViewAlert(vin: string) : IResponse
            Note over vpm,vps: CarNewsCenterManager calls upon<br>

            vps->>vps: Validate Parameters

            # Create default IPublicVehicleProfileDetails object

            # Send to data store
            vps->>+dg: ViewAlert(vin: string): IResponse
                Note over vps,dg: NotificationService calls upon SqlDCarNewsCenterTarget to generate<br>the sql statement and parameters

                dg->>+da: ExecuteWriteSQL(sqlCommands: ICollection<KeyValuePair<sql: string, sqlParameters: HashSet<SqlParameter>>>) : int
                    Note over dg,da: SqlDCarNewsCenterTarget calls upon<br>SqlServerDAO to execute the sql

                    da->>+ds: SqlCommand.ExecuteNonQuery() : Int
                        Note over da,ds: SqlServerDAO calls upon<br>`SqlCommand.ExecuteNonQuery()`<br>to execute the sql command

                        ds->>ds: SELECT (Description, Type, Date) FROM NotificationObject<br>INNER JOIN NotificationCenter <br>on NotificationObject.Notification_ID = NotificationCenter.Notification_ID 

                        ds->>ds:  Alerts are unsuccessfuly retrieved from DataStore

                    ds-->>-da: Database throws an exception

                    da->>da: Check for thrown exceptions

                da-->>-dg: IResponse object returned with<br>`IResponse.HasError` equal to true and<br>`IResponse.ErrorMessage` equal to the thrown exception

                dg->>dg: SqlDbVehicleTarget checks the error to see if the error is safe to retry

            dg-->>-vps: IResponse object returned with<br>`IResponse.IsSafeToRetry` updated

            vps->>vps: Check for errors in IResponseObject

            # Log unsuccessful vehicle creation
            vps-->>ll: CreateLogAsync(logLevel: string, logCategory: string, logContext: string, userHash: string) : IResponse
                Note over vps,ll: VehicleProfileCreationService calls upon LogService to log<br>successful creation of vehicle profile.<br>See logging success case

        vps-->>-vpm: IResponse object returned

        vpm->>vpm: Check for errors in returned IResponse object

        vpm->>vpm: Check for violation of business rules

        # Log unsuccessful vehicle creation
        vpm-->>ll: CreateLogAsync(logLevel: string, logCategory: string, logContext: string, userHash: string) : IResponse
            Note over vpm,ll: VehicleProfileManager calls upon LogService to log<br>successful creation of vehicle profile.<br>See logging success case

    vpm-->>-e: IResponse object returned

    e->>e: Check for errors in returned IResponse object

e-->>-u: Return StatusCode(500, IResponseObject.ErrorMessage)