sequenceDiagram
participant u as User
participant az as AuthN/AuthZ (Entry Point)
participant e as CommunicationEstablishmentPoint (Entry Point)
participant m as CommunicationEstablishmentManager (Manager Layer)
participant s as DealConfirmation (Service Layer)
participant cs as CreateChatSession (Service Layer)
participant ll as LogService (Services Layer)
participant dt as SqlDbCommunicationEstablishmentTarget (Data Gateway)
participant da as SqlServerDAO (Data Access Object)
participant ds as Data Store (Sql Server)
participant ll as LogService (Services Layer)

u->>+e: CancelDeal(seller: string, dealType: string) : IResponse
Note over u,e:  user cancels ongoing deal

e->>+m: CancelDeal(seller: string, dealType: string) : IResponse
m->>+s: DealCancellation(seller: string, dealType: string) : IResponse
s->>+dt: UpdateDealStatusSql(seller: string, dealType: string) : IResponse
dt->>+da: ExecuteWriteSQL(sqlCommands: ICollection<KeyValuePair<sql: string, sqlParameters: HashSet<SqlParameter>>>): int
da->>+ds: SqlCommand.ExecuteNonQuery() : int
ds->>ds: UPDATE MarketplaceStatus <br> SET MarketplaceStatus  = 0 <br> WHERE Vin = @Vin
ds->>da: Database executes update query
da-->>dt: Number of rows affected returned
dt-->>s: Response returned to service
s-->>m: Response returned to manager
m-->>e: Response returned to entry point
e-->>u: Return response to user

Note right of u: Vehicle profile status updated to "Available"